"use client";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NavBarVertical } from "@/components/static/frames/NavBarVertical";
import { NavBarHorizontal } from "@/components/static/frames/NavBarHorizontal";
import { Toaster } from "@/components/ui/toaster";
import useAuth from "./hooks/useAuth";
import Header from "@/components/layout/header";
import Sidebar from "@/components/layout/sidebar";

const font = Poppins({ weight: "400", subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { loggedIn } = useAuth();
  if (!loggedIn) {
    return (
      <html lang="en">
        <body className={font.className}>
          <div className="flex flex-col h-screen">
            <div className="flex flex-grow">
              <main className=" w-full">
                {children}
                <Toaster />
              </main>
            </div>
          </div>
        </body>
      </html>
    );
  } else {
    return (
      <html lang="en">
        <body className={font.className}>
          <div>
            {/* <NavBarHorizontal /> */}
            <Header />
            <div className="flex h-screen overflow-hidden">
              {/* <NavBarVertical /> */}
              <Sidebar />
              <main className=" w-full md:pt-16">
                {children}
                <Toaster />
              </main>
            </div>
          </div>
        </body>
      </html>
    );
  }
}
