services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app
    mem_limit: 256m  

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: yarn start:dev notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - '8003:8003'
    volumes:
      - .:/usr/src/app
    mem_limit: 20m

  organization:
    build:
      context: .
      dockerfile: ./apps/organization/Dockerfile
      target: development
    command: yarn start:dev organization
    env_file:
      - ./apps/organization/.env
    ports:
      - '8005:8005'
    volumes:
      - .:/usr/src/app
    mem_limit: 256m  

  agents:
    build:
      context: .
      dockerfile: ./apps/agents/Dockerfile
      target: development
    command: yarn start:dev agents
    env_file:
      - ./apps/agents/.env
    ports:
      - '8006:8006'
    volumes:
      - .:/usr/src/app
    mem_limit: 256m

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5433:5432'

      