services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
      - /usr/src/app/node_modules
      - /usr/src/app/apps/auth/node_modules

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: yarn start:dev notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - '8003:8003'
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
      - /usr/src/app/node_modules
      - /usr/src/app/apps/notifications/node_modules

  organization:
    build:
      context: .
      dockerfile: ./apps/organization/Dockerfile
      target: development
    command: yarn start:dev organization
    env_file:
      - ./apps/organization/.env
    ports:
      - '8009:8009'
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
      - /usr/src/app/node_modules
      - /usr/src/app/apps/organization/node_modules

  agents:
    build:
      context: .
      dockerfile: ./apps/agents/Dockerfile
      target: development
    command: yarn start:dev agents
    env_file:
      - ./apps/agents/.env
    ports:
      - '8006:8006'
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
      - /usr/src/app/node_modules
      - /usr/src/app/apps/agents/node_modules

  transaction:
    build:
      context: .
      dockerfile: ./apps/transaction/Dockerfile
      target: development
    command: yarn start:dev transaction
    env_file:
      - ./apps/transaction/.env
    ports:
      - '8010:8010'
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
      - /usr/src/app/node_modules
      - /usr/src/app/apps/transaction/node_modules

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - '5433:5432'
